FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir "setuptools<81" wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY ai-service/ ./ai-service/

EXPOSE 8000

CMD ["python", "ai-service/main.py"]
